#ifndef WLH_PROTOCOL_IDS_H
#define WLH_PROTOCOL_IDS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
enum {
    WLH_CHANNEL_LINK_CONTROL = 0x00,
    WLH_CHANNEL_CONTROL_RPC = 0x01,
    WLH_CHANNEL_ETHERNET_STA = 0x02,
    WLH_CHANNEL_ETHERNET_AP = 0x03,
    WLH_CHANNEL_BLUETOOTH_HCI = 0x04,
    WLH_CHANNEL_OTA_STREAM = 0x05,
    WLH_CHANNEL_DIAGNOSTIC_STREAM = 0x06,
    WLH_CHANNEL_LOG_STREAM = 0x07,
    WLH_CHANNEL_USER_PASSTHROUGH = 0x08
};

enum {
    WLH_SERVICE_INVALID = 0x0000,
    WLH_SERVICE_LINK = 0x0001,
    WLH_SERVICE_WIFI = 0x0002,
    WLH_SERVICE_BLUETOOTH = 0x0003,
    WLH_SERVICE_OTA = 0x0004,
    WLH_SERVICE_DIAGNOSTICS = 0x0005,
    WLH_SERVICE_IO = 0x0006,
    WLH_SERVICE_ADC = 0x0007,
    WLH_SERVICE_KV = 0x0008,
    WLH_SERVICE_DEVICE_INFO = 0x0009,
    WLH_SERVICE_USER_PASSTHROUGH = 0x000f
};

enum {
    WLH_LINK_METHOD_HELLO = 0x0001,
    WLH_LINK_METHOD_CREDIT_UPDATE = 0x0002,
    WLH_LINK_METHOD_HEARTBEAT = 0x0003,
    WLH_LINK_METHOD_CHANNEL_RESET = 0x0004,

    WLH_LINK_EVENT_SESSION_CHANGED = 0x8001
};

enum {
    WLH_WIFI_METHOD_INITIALIZE = 0x0001,
    WLH_WIFI_METHOD_DEINITIALIZE = 0x0002,
    WLH_WIFI_METHOD_SCAN_START = 0x0003,
    WLH_WIFI_METHOD_SCAN_CANCEL = 0x0004,
    WLH_WIFI_METHOD_CONNECT = 0x0005,
    WLH_WIFI_METHOD_DISCONNECT = 0x0006,
    WLH_WIFI_METHOD_GET_LINK_INFO = 0x0007,
    WLH_WIFI_METHOD_SET_COUNTRY = 0x0008,
    WLH_WIFI_METHOD_GET_COUNTRY = 0x0009,
    WLH_WIFI_METHOD_SET_POWER_MODE = 0x000a,
    WLH_WIFI_METHOD_GET_POWER_MODE = 0x000b,
    WLH_WIFI_METHOD_GET_STATISTICS = 0x000c,
    WLH_WIFI_METHOD_START_AP = 0x000d,
    WLH_WIFI_METHOD_STOP_AP = 0x000e,
    WLH_WIFI_METHOD_GET_AP_CLIENTS = 0x000f,

    WLH_WIFI_EVENT_SCAN_RESULT = 0x8001,
    WLH_WIFI_EVENT_SCAN_COMPLETED = 0x8002,
    WLH_WIFI_EVENT_CONNECTED = 0x8003,
    WLH_WIFI_EVENT_DISCONNECTED = 0x8004,
    WLH_WIFI_EVENT_AP_CLIENT_JOINED = 0x8005,
    WLH_WIFI_EVENT_AP_CLIENT_LEFT = 0x8006
};

enum {
    WLH_BLUETOOTH_METHOD_INITIALIZE = 0x0001,
    WLH_BLUETOOTH_METHOD_DEINITIALIZE = 0x0002,
    WLH_BLUETOOTH_METHOD_ENABLE = 0x0003,
    WLH_BLUETOOTH_METHOD_DISABLE = 0x0004,
    WLH_BLUETOOTH_METHOD_GET_INFO = 0x0005,

    WLH_BLUETOOTH_EVENT_STATE_CHANGED = 0x8001
};

/* HCI Raw Records on WLH_CHANNEL_BLUETOOTH_HCI use the H4 packet type as
 * record_type; the record payload excludes the H4 type octet. */
enum {
    WLH_H4_TYPE_COMMAND = 0x01,
    WLH_H4_TYPE_ACL = 0x02,
    WLH_H4_TYPE_SCO = 0x03,
    WLH_H4_TYPE_EVENT = 0x04,
    WLH_H4_TYPE_ISO = 0x05
};

enum {
    WLH_OTA_METHOD_BEGIN = 0x0001,
    WLH_OTA_METHOD_FINALIZE = 0x0002,
    WLH_OTA_METHOD_ABORT = 0x0003,
    WLH_OTA_METHOD_ACTIVATE = 0x0004,
    WLH_OTA_METHOD_QUERY = 0x0005,

    WLH_OTA_EVENT_PROGRESS = 0x8001
};

enum {
    WLH_DIAGNOSTICS_METHOD_PING = 0x0001,
    WLH_DIAGNOSTICS_METHOD_GET_STATISTICS = 0x0002,
    WLH_DIAGNOSTICS_METHOD_SET_LOG = 0x0003,
    WLH_DIAGNOSTICS_METHOD_RESET_COPROCESSOR = 0x0004,

    WLH_DIAGNOSTICS_EVENT_FAULT = 0x8001
};

enum {
    WLH_IO_METHOD_CONFIGURE = 0x0001,
    WLH_IO_METHOD_READ = 0x0002,
    WLH_IO_METHOD_WRITE = 0x0003
};

enum { WLH_ADC_METHOD_READ = 0x0001 };

enum {
    WLH_KV_METHOD_READ = 0x0001,
    WLH_KV_METHOD_WRITE = 0x0002,
    WLH_KV_METHOD_ERASE = 0x0003
};

enum { WLH_DEVICE_INFO_METHOD_GET_INFO = 0x0001 };

enum {
    WLH_USER_PASSTHROUGH_METHOD_SEND = 0x0001,

    WLH_USER_PASSTHROUGH_EVENT_RESULT = 0x8001
};

typedef enum wlh_status_domain {
    WLH_STATUS_DOMAIN_NONE = 0,
    WLH_STATUS_DOMAIN_PROTOCOL = 1,
    WLH_STATUS_DOMAIN_TRANSPORT = 2,
    WLH_STATUS_DOMAIN_LINK = 3,
    WLH_STATUS_DOMAIN_WIFI = 4,
    WLH_STATUS_DOMAIN_BLUETOOTH = 5,
    WLH_STATUS_DOMAIN_OTA = 6,
    WLH_STATUS_DOMAIN_PERIPHERAL = 7,
    WLH_STATUS_DOMAIN_STORAGE = 8,
    WLH_STATUS_DOMAIN_DEVICE_INFO = 9,
    WLH_STATUS_DOMAIN_USER = 10,
    WLH_STATUS_DOMAIN_VENDOR_MIN = 0x8000
} wlh_status_domain_t;

typedef enum wlh_status_code {
    WLH_STATUS_OK = 0,
    WLH_STATUS_INVALID_ARGUMENT = -1,
    WLH_STATUS_NOT_SUPPORTED = -2,
    WLH_STATUS_NOT_READY = -3,
    WLH_STATUS_BUSY = -4,
    WLH_STATUS_WOULD_BLOCK = -5,
    WLH_STATUS_NO_MEMORY = -6,
    WLH_STATUS_NO_CREDIT = -7,
    WLH_STATUS_TIMEOUT = -8,
    WLH_STATUS_CANCELLED = -9,
    WLH_STATUS_VERSION_MISMATCH = -10,
    WLH_STATUS_SESSION_CHANGED = -11,
    WLH_STATUS_TRANSPORT_FAILURE = -12,
    WLH_STATUS_PEER_UNRESPONSIVE = -13,
    WLH_STATUS_AUTHENTICATION_FAILED = -14,
    WLH_STATUS_NOT_FOUND = -15,
    WLH_STATUS_ALREADY_EXISTS = -16,
    WLH_STATUS_PERMISSION_DENIED = -17,
    WLH_STATUS_DATA_LOSS = -18,
    WLH_STATUS_RESOURCE_EXHAUSTED = -19,
    WLH_STATUS_INTERNAL = -20
} wlh_status_code_t;

#ifdef __cplusplus
}
#endif

#endif
